version = 1
SPDX-PackageName = "SPIRV-Visualizer"
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/SPIRV-Visualizer"

[[annotations]]
precedence = "closest"
path = [
    "**",
]
SPDX-FileCopyrightText = "The Khronos Group, Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
precedence = "closest"
path = [
    "lib/qunit/qunit-2.13.0.css",
    "lib/qunit/qunit-2.13.0.min.js",
]
SPDX-FileCopyrightText = "OpenJS Foundation and other contributors"
SPDX-License-Identifier = "MIT"
